import PDFDocument from "pdfkit";
import { getModel } from "../utils/llmModel.js";
import { uploadToS3 } from "../utils/uploadToS3.js";
import { getDownloadUrl } from "../utils/getDownloadUrl.js";
import { deductCredits } from "../utils/deductCredit.js";

export const pdfAgent = async (state) => {
  try {
    await deductCredits(state.userId, "pdf");

    // IMPORTANT:
    // Use await if getModel() is async
    const llm = await getModel("pdf");

    const aiResponse = await llm.invoke(`
Create a professional document about:

${state.prompt}

Rules:
- Generate a professional title.
- Generate an introduction.
- Generate multiple sections.
- Generate bullet points where required.
- Generate a conclusion.
- No markdown.
- No code blocks.
- No ** symbols.
- No ### headings.
- Return plain text only.
`);

    const rawContent = aiResponse?.content?.trim() || state.prompt;

    const lines = rawContent.split("\n").filter((line) => line.trim());

    const generatedTitle =
      lines.length > 0 && lines[0].length < 120 ? lines[0] : state.prompt;

    const cleanContent = rawContent
      .replace(/\*\*/g, "")
      .replace(/```/g, "")
      .replace(/###/g, "")
      .replace(/##/g, "")
      .replace(/#/g, "")
      .trim();

    // Correct filename
    const fileName = `pdf-${Date.now()}.pdf`;

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      bufferPages: true,
      info: {
        Title: generatedTitle,
        Author: "CortexAI",
        Subject: state.prompt,
        Creator: "CortexAI PDF Agent",
      },
    });

    const chunks = [];

    doc.on("data", (chunk) => {
      chunks.push(chunk);
    });

    doc.on("error", (error) => {
      console.error("PDFKit Error:", error);
    });

    // Title
    doc.fontSize(26).fillColor("#111827").text(generatedTitle, {
      align: "center",
    });

    doc.moveDown();

    // Date
    doc
      .fontSize(10)
      .fillColor("#6B7280")
      .text(`Generated on ${new Date().toLocaleString()}`, {
        align: "center",
      });

    doc.moveDown(3);

    // Content
    doc.fontSize(12).fillColor("#374151").text(cleanContent, {
      align: "left",
      lineGap: 6,
    });

    doc.moveDown(2);

    // Footer
    doc.fontSize(10).fillColor("#9CA3AF").text("Generated by CortexAI", {
      align: "center",
    });

    doc.end();

    await new Promise((resolve, reject) => {
      doc.on("end", resolve);
      doc.on("error", reject);
    });

    const pdfBuffer = Buffer.concat(chunks);

    // Upload PDF
    await uploadToS3(pdfBuffer, fileName, "application/pdf");

    // 24 hours
    const downloadUrl = await getDownloadUrl(fileName, 24 * 60 * 60);

    return {
      ...state,

      response: `
# PDF Generated Successfully

📄 ${generatedTitle}

📥 [Download PDF](${downloadUrl})

⏳ Link expires in 24 hours.
`.trim(),

      artifacts: [
        {
          type: "pdf",
          name: fileName,
          url: downloadUrl,
        },
      ],
    };
  } catch (error) {
    console.error("PDF Agent Error:", error);

    return {
      ...state,
      response: "Failed to generate PDF.",
      artifacts: [],
    };
  }
};
